/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SavedRouteImport } from './routes/saved'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CollegesRouteImport } from './routes/colleges'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CollegeSlugRouteImport } from './routes/college.$slug'

const SavedRoute = SavedRouteImport.update({
  id: '/saved',
  path: '/saved',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegesRoute = CollegesRouteImport.update({
  id: '/colleges',
  path: '/colleges',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CollegeSlugRoute = CollegeSlugRouteImport.update({
  id: '/college/$slug',
  path: '/college/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/college/$slug': typeof CollegeSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/college/$slug': typeof CollegeSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/colleges': typeof CollegesRoute
  '/contact': typeof ContactRoute
  '/profile': typeof ProfileRoute
  '/saved': typeof SavedRoute
  '/college/$slug': typeof CollegeSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/colleges'
    | '/contact'
    | '/profile'
    | '/saved'
    | '/college/$slug'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/colleges' | '/contact' | '/profile' | '/saved' | '/college/$slug'
  id:
    | '__root__'
    | '/'
    | '/colleges'
    | '/contact'
    | '/profile'
    | '/saved'
    | '/college/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CollegesRoute: typeof CollegesRoute
  ContactRoute: typeof ContactRoute
  ProfileRoute: typeof ProfileRoute
  SavedRoute: typeof SavedRoute
  CollegeSlugRoute: typeof CollegeSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/saved': {
      id: '/saved'
      path: '/saved'
      fullPath: '/saved'
      preLoaderRoute: typeof SavedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colleges': {
      id: '/colleges'
      path: '/colleges'
      fullPath: '/colleges'
      preLoaderRoute: typeof CollegesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/college/$slug': {
      id: '/college/$slug'
      path: '/college/$slug'
      fullPath: '/college/$slug'
      preLoaderRoute: typeof CollegeSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CollegesRoute: CollegesRoute,
  ContactRoute: ContactRoute,
  ProfileRoute: ProfileRoute,
  SavedRoute: SavedRoute,
  CollegeSlugRoute: CollegeSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
